// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxlfiAMWQFGA6XGXLYu2z4nczrMYGRaY4',
    appId: '1:619414789704:web:a56af37d4a475f963a027d',
    messagingSenderId: '619414789704',
    projectId: 'snel-69ae7',
    authDomain: 'snel-69ae7.firebaseapp.com',
    storageBucket: 'snel-69ae7.appspot.com',
    measurementId: 'G-SF3KBM4NM7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjxWMTzjKt4EMq_q65Ey3fMC19BcEmqZc',
    appId: '1:619414789704:android:a2e4f4a866c6d6d23a027d',
    messagingSenderId: '619414789704',
    projectId: 'snel-69ae7',
    storageBucket: 'snel-69ae7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6rBoi5hxOSDnSTcskaJL-DtA_1OMcU9Y',
    appId: '1:619414789704:ios:96339ea93f3f4f163a027d',
    messagingSenderId: '619414789704',
    projectId: 'snel-69ae7',
    storageBucket: 'snel-69ae7.appspot.com',
    iosBundleId: 'com.logiv.snel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6rBoi5hxOSDnSTcskaJL-DtA_1OMcU9Y',
    appId: '1:619414789704:ios:e5041ff3c5b48e823a027d',
    messagingSenderId: '619414789704',
    projectId: 'snel-69ae7',
    storageBucket: 'snel-69ae7.appspot.com',
    iosBundleId: 'com.logiv.snel.RunnerTests',
  );
}
